[Session]
bind_address = 0.0.0.0:5001
address = 127.0.0.1:5001
sender_comp_id = SENDER
target_comp_id = TARGET
heartbeat_interval = 30
ssl_cert_file = 
ssl_key_file = 
ssl_ca_file = 

[Scheduler]
# Example schedules JSON: [["action", "HH:MM"]]
schedules = [["reset", "00:00"], ["start", "08:00"], ["stop/logout", "18:00"]]
